name: Update Changelog on Merge to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update_changelog:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Generate Changelog
      run: |
        bundle exec github_changelog_generator \
          --user ${{ github.repository_owner }} \
          --project ${{ github.event.repository.name }} \
          --token ${{ secrets.GITHUB_TOKEN }}

    - name: Commit Changelog
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG.md for PR #${{ github.event.pull_request.number }}"
        git push origin main
